### ISSUE TITLE
Multi-line messages out of order

### ISSUE THREAD

**Issue by broofa** [gf3/Jerk#13]
When I send a multiline message (i.e. a message with \n's separating lines of text), the messages often appear out of order in IRC.

Is this an issue with IRC in general, or something specific to Jerk or irc.js?

**Comment by gf3** [comment]
Hmm, sounds like it might be an issue with the flood protection in IRC-js. Is it just the first line that is out of order?

**Comment by broofa** [comment]
It's more than just the first line.  E.g. if I do message.say(['a', 'b', 'c', d'].join('\n')), what I see in IRC is ...
    a
    d
    c
    b

This looks like it's a jerk/irc.js issue, btw.  The [SENT] log messages on the command line show the messages are being sent out of order.

**Comment by gf3** [comment]
Ahhhh, it's sending the first message immediately and then queueing the rest, but it is going through the queue backwards. This is fixed and live in `1.1.4`.

**Comment by broofa** [comment]
Awesome.  Thanks for the quick response, and for a nifty module - 'been having a lot of fun with it!

**Comment by gf3** [comment]
No problem, so glad to hear you're having fun with it! Take care.
