### ISSUE TITLE
coloured & log dependencies are not declared in package.json

### ISSUE THREAD

**Issue by beriberikix** [gf3/Jerk#15]
Coloured & log are not declared as dependencies in the package.json file, so when you install with NPM, they are not included. Then your commandline **weeps**.

**Comment by jsyrjala** [comment]
The exception comes from jerk/node_modules/irc-js/node_modules/coloured-log/lib/coloured-log.js:1:76.

Also the current version of Jerk (1.1.15) depends on "irc-js": "=0.2.23", while the newest irc-js is 0.2.26. The colored log thing was removed in irc-js 0.2.26.
