### ISSUE TITLE
Remove node_modules directory?

### ISSUE THREAD

**Issue by jsyrjala** [gf3/Jerk#18]
Currently jerk has [node_modules](https://github.com/gf3/Jerk/tree/master/node_modules) directory that contains a version of [irc-js](https://github.com/gf3/Irc-js/) library. However the jerk's [package.json](https://github.com/gf3/Jerk/blob/master/package.json) lists `irc-js` as dependecy.

I think that npm will download irc-js just based on package.json when installing jerk, so jerk's node_modules directory could be removed complitely.

**Comment by gf3** [comment]
Yes, I'm actually in the process of doing this for both Jerk and IRC-js. Expect updates soon!
