### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by jmzrlz** [gf3/Jerk#24]
I see that you've coded this in such a way that, even if you try to initialise it twice and pass two different sets of options, it will use the same instance.

I'm porting a bot of mine from python to JS, it involves having two connections running simultaneously and the two 'bots' communicating with each other.

Is it possible for you to alter it so this is possible?

**Comment by gf3** [comment]
This should be fixed in the latest version, based on IRC-js 2.0.0-beta
