### ISSUE TITLE
Add reference to underlying irc-js object

### ISSUE THREAD

**Issue by pyropeter** [gf3/Jerk#9]
It would be useful to know properties of the irc-js instance at times:

``` javascript
  j.watch_for(/^(.*?): leave/i, function (msg) {
    if (msg.match_data[1] == j.bot.options.nick)
      j.part(msg.source);
  });
```

At the moment, one has to call e.g. `jerkinstance.say("", "foo")` to get a reference to the underlying irc-js layer.

**Comment by gf3** [comment]
So you'd like direct access to `bot`?

**Comment by pyropeter** [comment]
Exactly.

Maybe `bot` could be made the return value of `jerk().connect()`?
